/*
    This the file generated by the productivity prompts.
*/

package org.onebeartoe;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

public class ImageMarkdownGenerator {

    private static final List<String> IMAGE_EXTENSIONS = Arrays.asList(".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp");

    public static void main(String[] args) {
        File currentDir = new File(".");
        File[] files = currentDir.listFiles();

        if (files == null) {
            System.err.println("Could not list files in the current directory.");
            return;
        }

        List<File> imageFiles = Arrays.stream(files)
                .filter(File::isFile)
                .filter(file -> isImage(file.getName().toLowerCase()))
                .sorted((f1, f2) -> f1.getName().compareToIgnoreCase(f2.getName()))
                .collect(Collectors.toList());

        if (imageFiles.isEmpty()) {
            System.out.println("No image files found in the current directory.");
            return;
        }

        String timestamp = new SimpleDateFormat("yyyy-MM-dd-HHmm").format(new Date());
        String outputFileName = "images-" + timestamp + ".md";

        try (FileWriter writer = new FileWriter(outputFileName)) {
            writer.write("# Images Found on " + timestamp + "\n\n");
            for (File imageFile : imageFiles) {
                String fileName = imageFile.getName();
                writer.write("<img src=\"" + fileName + "\" alt=\"" + fileName + "\" width=\"50%\" height=\"50%\" />\n\n");
            }
            System.out.println("Markdown file created: " + outputFileName);
        } catch (IOException e) {
            System.err.println("An error occurred while writing the Markdown file: " + e.getMessage());
        }
    }

    private static boolean isImage(String fileName) {
        return IMAGE_EXTENSIONS.stream().anyMatch(fileName::endsWith);
    }
}
